name       : libusb-compat
version    : 0.1.5
release    : 1
source     :
    - https://netcologne.dl.sourceforge.net/project/libusb/libusb-compat-0.1/libusb-compat-0.1.5/libusb-compat-0.1.5.tar.bz2 : 404ef4b6b324be79ac1bfb3d839eac860fbc929e6acb1ef88793a6ea328bc55a
license    : LGPL-2.1
component  : system.utils
summary    : libusb-1.0 Compatibility Layer for libusb-0.1
description: |
    A compatibility layer allowing applications written for libusb-0.1 to work with libusb-1.0. libusb-compat-0.1 attempts to look, feel, smell and walk like libusb-0.1.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
