name       : libusb-compat
version    : 0.1.7
release    : 4
source     :
    - https://github.com/libusb/libusb-compat-0.1/releases/download/v0.1.7/libusb-compat-0.1.7.tar.gz : 0679ce38aa02498c1eea9c13398a0d2356883d574632a59c1e25274ed4925cf8
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libusb-1.0 Compatibility Layer for libusb-0.1
description: |
    A compatibility layer allowing applications written for libusb-0.1 to work with libusb-1.0. libusb-compat-0.1 attempts to look, feel, smell and walk like libusb-0.1.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
